// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhp5T1XINdH8vaJBRkOM1Ks3AlJ0xzOKA',
    appId: '1:977095050295:web:666845e59230f326cb6bb2',
    messagingSenderId: '977095050295',
    projectId: 'foodi-49d81',
    authDomain: 'foodi-49d81.firebaseapp.com',
    storageBucket: 'foodi-49d81.appspot.com',
    measurementId: 'G-CZ6M6HGENV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByl-k6IT6AKD5qRx4DuyAyeEXNb3gaRHA',
    appId: '1:977095050295:android:5c38afd59f60e015cb6bb2',
    messagingSenderId: '977095050295',
    projectId: 'foodi-49d81',
    storageBucket: 'foodi-49d81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATAyKnZjJGRfG8ymf6EWv3cungqdVRZ4s',
    appId: '1:977095050295:ios:e87110268b940a49cb6bb2',
    messagingSenderId: '977095050295',
    projectId: 'foodi-49d81',
    storageBucket: 'foodi-49d81.appspot.com',
    iosBundleId: 'com.example.providerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATAyKnZjJGRfG8ymf6EWv3cungqdVRZ4s',
    appId: '1:977095050295:ios:eb6438b6bc331471cb6bb2',
    messagingSenderId: '977095050295',
    projectId: 'foodi-49d81',
    storageBucket: 'foodi-49d81.appspot.com',
    iosBundleId: 'com.example.providerapp.RunnerTests',
  );
}
